/**
 * No half-resolved merge may reach the tree.
 *
 * `.github/workflows/conflict-check.yml` (#845/#861) greps changed files for
 * `<<<<<<<`, `=======` and `>>>>>>>`. That is the right check and it missed
 * what actually happened in 58e2d84 (#872): the conflict was resolved by
 * deleting the marker *prefixes* and leaving their tails behind, so `main`
 * ended up with
 *
 *     <h1 className="mb-4">🚀 AI Resume Analyzer</h1>
 *      feature/document-semver-process-756
 *
 * in App.tsx — legal JSX, so it compiled, typechecked, and rendered the branch
 * name to every visitor — and
 *
 *      feature/document-semver-process-756
 *     # Generated by Django 6.1 on 2026-08-24 07:43
 *
 * as line 1 of a migration, which does not parse at all.
 *
 * This lives in the suite rather than only in a workflow so it is runnable
 * before pushing, and so it fails with a message rather than a red square in
 * a tab nobody opens.
 */

import { execFileSync } from 'node:child_process'
import { readFileSync } from 'node:fs'
import path from 'node:path'

import { describe, expect, it } from 'vitest'

const REPO_ROOT = path.resolve(__dirname, '..', '..', '..')

/** Source languages where a bare word on its own line is never intentional. */
const SCANNED = /\.(ts|tsx|js|jsx|mjs|cjs|py|css|scss|json|yml|yaml)$/

const SKIPPED = [
  'node_modules/',
  'package-lock.json',
  'dist/',
  'build/',
  // This file quotes the very patterns it looks for.
  'src/__tests__/conflictResidue.test.ts',
  '.github/workflows/conflict-check.yml',
]

/** Full conflict markers, including the diff3 `|||||||` variant. */
const MARKER = /^(<{7}|={7}|>{7}|\|{7})(\s|$)/

/**
 * What a stripped marker leaves behind: one space, then the ref that was on
 * the marker line.
 *
 * Deliberately narrow. It requires the leading space git puts there, and a ref
 * that either is one of the usual merge targets or contains a `/` the way
 * branch names conventionally do. A line of real code that is a single space
 * followed by nothing but `feature/x` or `main` does not occur in any of the
 * scanned languages — including JSX, where it would be a text node reading
 * "main".
 */
const RESIDUE = /^ (?:main|master|HEAD|origin\/[\w./-]+|[\w.-]+\/[\w./-]+)$/

function trackedFiles(): string[] {
  const out = execFileSync('git', ['ls-files', '-z'], {
    cwd: REPO_ROOT,
    encoding: 'utf8',
    maxBuffer: 32 * 1024 * 1024,
  })
  return out.split('\0').filter(Boolean)
}

function scan(pattern: RegExp): string[] {
  const hits: string[] = []

  for (const file of trackedFiles()) {
    if (!SCANNED.test(file)) continue
    if (SKIPPED.some((prefix) => file.startsWith(prefix) || file.includes(`/${prefix}`))) continue

    let text: string
    try {
      text = readFileSync(path.join(REPO_ROOT, file), 'utf8')
    } catch {
      continue // a deleted-but-still-indexed path, or a binary blob
    }

    text.split('\n').forEach((line, index) => {
      if (pattern.test(line)) hits.push(`${file}:${index + 1}: ${line}`)
    })
  }

  return hits
}

describe('no merge conflict residue in the tree (#872)', () => {
  it('has no conflict markers', () => {
    expect(scan(MARKER)).toEqual([])
  })

  it('has no stripped-marker leftovers', () => {
    // What this catches, and what the grep in conflict-check.yml cannot:
    // resolving a conflict by deleting `<<<<<<< ` and `>>>>>>> ` rather than
    // the whole line.
    expect(scan(RESIDUE)).toEqual([])
  })
})

describe('the residue pattern itself', () => {
  const matches = (line: string) => RESIDUE.test(line)

  it('matches the shapes git actually leaves', () => {
    expect(matches(' main')).toBe(true)
    expect(matches(' master')).toBe(true)
    expect(matches(' HEAD')).toBe(true)
    expect(matches(' feature/document-semver-process-756')).toBe(true)
    expect(matches(' origin/main')).toBe(true)
  })

  it('does not match ordinary code', () => {
    expect(matches('main')).toBe(false) // no leading space
    expect(matches('  main')).toBe(false) // indented code, not a marker tail
    expect(matches(' main()')).toBe(false)
    expect(matches(' import main from "./main"')).toBe(false)
    expect(matches(' a / b')).toBe(false)
    expect(matches('')).toBe(false)
  })

  it('matches every full marker form, diff3 included', () => {
    expect(MARKER.test('<<<<<<< HEAD')).toBe(true)
    expect(MARKER.test('=======')).toBe(true)
    expect(MARKER.test('>>>>>>> origin/main')).toBe(true)
    expect(MARKER.test('||||||| merged common ancestors')).toBe(true)
    // A markdown rule and a Python comment banner are not markers.
    expect(MARKER.test('======')).toBe(false)
    expect(MARKER.test('# =======================')).toBe(false)
  })
})
