# Generated by Django 5.2.16 on 2026-07-31 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0002_analysisresult"),
        ("analyzer", "0008_resumeanalysis_interview_questions"),
        ("analyzer", "0008_userprofile"),
    ]

    operations = []
