# Generated by Django 5.2.16 on 2026-08-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0009_merge_20260801_0119"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnalysisResult",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="weekly_digest_opt_in",
            field=models.BooleanField(default=False),
        ),
    ]
