# Generated by Django 5.2.17 on 2026-08-10 09:56

from django.db import migrations


def populate_role_skills(apps, schema_editor):
    Role = apps.get_model('analyzer', 'Role')
    Skill = apps.get_model('analyzer', 'Skill')
    ROLE_SKILLS = {
        "Frontend Developer": [
            "html", "css", "javascript", "typescript", "react",
            "next.js", "tailwind", "git", "github", "webpack",
        ],
        "Backend Developer": [
            "python", "django", "flask", "fastapi", "node.js", "express.js",
            "sql", "mysql", "postgresql", "mongodb", "docker", "git", "github",
        ],
        "Data Analyst": [
            "python", "sql", "excel", "machine learning", "deep learning",
            "data analysis", "pandas", "numpy", "matplotlib", "tensorflow",
            "scikit-learn", "jupyter",
        ],
    }

    for role_name, skills_list in ROLE_SKILLS.items():
        role, _ = Role.objects.get_or_create(name=role_name)
        for skill_name in skills_list:
            skill, _ = Skill.objects.get_or_create(name=skill_name)
            role.skills.add(skill)


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0011_role_skills_schema'),
    ]

    operations = [
        migrations.RunPython(populate_role_skills),
    ]
