# Generated by Django 6.1 on 2026-08-16 12:31
#
# The Webhook model was added to models.py in #549 without a migration, so the
# table has never existed. That did not only break webhooks: User has a cascade
# into it, so `User.delete()` raised "no such table: analyzer_webhook" on any
# database migrated from scratch. See #631.

import analyzer.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0013_suggestionfeedback"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "secret",
                    models.CharField(
                        default=analyzer.models.generate_webhook_secret, max_length=64
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_delivery_at", models.DateTimeField(blank=True, null=True)),
                ("last_status_code", models.IntegerField(blank=True, null=True)),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "url"), name="unique_webhook_url_per_user"
                    )
                ],
            },
        ),
    ]
