# Generated by Django 5.2.17 on 2026-08-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0014_webhook"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeanalysis",
            name="experience_level",
            field=models.CharField(blank=True, default="Mid-Level", max_length=50),
        ),
    ]
