# Generated by Django 6.1 on 2026-08-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0018_userprofile_notification_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='jd_matched_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='jd_missing_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='job_match_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
