# Generated by Django 6.1 on 2026-08-23 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0019_batchupload'),
        ('analyzer', '0019_resumeanalysis_jd_matched_skills_and_more'),
    ]

    operations = [
    ]
