# Generated by Django 6.1 on 2026-08-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0019_batchupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), (
                'system', 'System')], default='system', max_length=10),
        ),
    ]
