# Generated by Django 6.1 on 2026-08-24 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0020_merge_20260824_0025'),
        ('analyzer', '0020_resumebadge'),
    ]

    operations = [
    ]
