# Generated by Django 6.1 on 2026-08-31 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0021_merge_resumebadge_and_jd_match_fields'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='skill',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('org', 'name'), name='unique_role_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('org', 'name'), name='unique_skill_name_per_org'),
        ),
    ]
