# Generated by Django on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0022_applicationlog'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='resumeanalysis',
            index=models.Index(fields=['user', '-created_at', '-id'], name='analyzer_re_user_id_44bdcd_idx'),
        ),
        migrations.AddIndex(
            model_name='resumeanalysis',
            index=models.Index(fields=['target_role'], name='analyzer_re_target__f4dbca_idx'),
        ),
    ]
