# Generated by Django 6.1 on 2026-08-30 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0023_resumeanalysis_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="resumeanalysis",
            new_name="analyzer_re_user_id_99ae9c_idx",
            old_name="analyzer_re_user_id_44bdcd_idx",
        ),
        migrations.RenameIndex(
            model_name="resumeanalysis",
            new_name="analyzer_re_target__df6354_idx",
            old_name="analyzer_re_target__f4dbca_idx",
        ),
    ]
