# Generated by Django 6.1 on 2026-08-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0024_rename_analyzer_re_user_id_44bdcd_idx_analyzer_re_user_id_99ae9c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupAbuseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('signup_count', models.IntegerField(help_text='Number of signups in the time window')),
                ('window_minutes', models.IntegerField(help_text='The time window in minutes')),
                ('user_agent', models.TextField(blank=True, help_text='The user agent of the last request')),
                ('status', models.CharField(choices=[('flagged', 'Flagged'), ('throttled', 'Throttled'), ('reviewed', 'Reviewed')], default='flagged', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Maintainer notes')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
