# Generated by Django on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0025_signupabuseevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Short bio or professional headline.',
                max_length=250,
            ),
        ),
    ]
