# Generated by Django 6.1 on 2026-09-01 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0026_userprofile_bio'),
        ('analyzer', '0022_add_org_to_skill_and_role'),
    ]

    operations = [
    ]
