# Generated by Django 5.2.17 on 2026-09-01 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0021_merge_0020_merge_20260824_0025_0020_resumebadge'),
        ('analyzer', '0021_merge_20260824_1342'),
        ('analyzer', '0021_merge_20260824_1350'),
        ('analyzer', '0026_userprofile_tier'),
        ('analyzer', '0027_merge_20260901_0900'),
    ]

    operations = [
    ]
