"""
Branding Services for White-label Customization
Core business logic for branding management.
"""

import logging
import re
import hashlib
from typing import Dict, Any, Optional, Tuple
from django.core.cache import cache
from django.core.files.uploadedfile import UploadedFile

from .models import OrganizationBranding, BRANDING_TEMPLATES

logger = logging.getLogger(__name__)


class BrandingService:
    """
    Service class for branding operations.
    Handles CSS generation, logo validation, and caching.
    """
    
    def __init__(self):
        self.cache_prefix = 'branding_'
    
    def generate_branding_css(self, branding: OrganizationBranding) -> str:
        """
        Generate CSS from branding settings.
        
        Args:
            branding: OrganizationBranding object
        
        Returns:
            CSS string
        """
        # Base CSS
        css = f"""
        /* ========================================
           Branding CSS - {branding.brand_name or 'Custom'}
           Generated by White-label Service
           ======================================== */
        
        :root {{
            --brand-primary: {branding.primary_color};
            --brand-secondary: {branding.secondary_color};
            --brand-accent: {branding.accent_color};
            --brand-background: {branding.background_color};
            --brand-text: {branding.text_color};
            --brand-link: {branding.link_color};
            --brand-font: '{branding.primary_font}', {branding.secondary_font}, system-ui, sans-serif;
            --brand-font-size: {branding.font_size};
            --brand-border-radius: {branding.widget_border_radius};
            --brand-shadow: {branding.widget_shadow};
            --brand-logo-width: {branding.logo_width}px;
            --brand-logo-height: {branding.logo_height}px;
        }}
        
        /* ========================================
           Base Styles
           ======================================== */
        
        .brand-container {{
            font-family: var(--brand-font);
            font-size: var(--brand-font-size);
            color: var(--brand-text);
            background: var(--brand-background);
        }}
        
        /* ========================================
           Color Utilities
           ======================================== */
        
        .brand-primary {{ color: var(--brand-primary); }}
        .brand-secondary {{ color: var(--brand-secondary); }}
        .brand-accent {{ color: var(--brand-accent); }}
        .brand-text {{ color: var(--brand-text); }}
        .brand-background {{ background: var(--brand-background); }}
        
        .brand-bg-primary {{ background-color: var(--brand-primary); }}
        .brand-bg-secondary {{ background-color: var(--brand-secondary); }}
        .brand-bg-accent {{ background-color: var(--brand-accent); }}
        
        .brand-border-primary {{ border-color: var(--brand-primary); }}
        .brand-border-secondary {{ border-color: var(--brand-secondary); }}
        
        /* ========================================
           Links
           ======================================== */
        
        .brand-link {{
            color: var(--brand-link);
            text-decoration: none;
            transition: color 0.2s ease;
        }}
        .brand-link:hover {{
            color: var(--brand-primary);
            text-decoration: underline;
        }}
        
        /* ========================================
           Buttons
           ======================================== */
        
        .brand-btn-primary {{
            background: var(--brand-primary);
            color: #FFFFFF;
            border: none;
            padding: 10px 24px;
            border-radius: var(--brand-border-radius);
            font-family: var(--brand-font);
            font-weight: 600;
            font-size: 14px;
            cursor: pointer;
            transition: all 0.3s ease;
            box-shadow: 0 2px 4px rgba(0,0,0,0.05);
        }}
        .brand-btn-primary:hover {{
            background: var(--brand-secondary);
            transform: translateY(-2px);
            box-shadow: var(--brand-shadow);
        }}
        .brand-btn-primary:active {{
            transform: translateY(0);
        }}
        
        .brand-btn-secondary {{
            background: var(--brand-secondary);
            color: #FFFFFF;
            border: none;
            padding: 10px 24px;
            border-radius: var(--brand-border-radius);
            font-family: var(--brand-font);
            font-weight: 600;
            font-size: 14px;
            cursor: pointer;
            transition: all 0.3s ease;
        }}
        .brand-btn-secondary:hover {{
            background: var(--brand-primary);
            transform: translateY(-2px);
            box-shadow: var(--brand-shadow);
        }}
        
        .brand-btn-outline {{
            background: transparent;
            color: var(--brand-primary);
            border: 2px solid var(--brand-primary);
            padding: 8px 22px;
            border-radius: var(--brand-border-radius);
            font-family: var(--brand-font);
            font-weight: 600;
            font-size: 14px;
            cursor: pointer;
            transition: all 0.3s ease;
        }}
        .brand-btn-outline:hover {{
            background: var(--brand-primary);
            color: #FFFFFF;
            transform: translateY(-2px);
        }}
        
        /* ========================================
           Cards
           ======================================== */
        
        .brand-card {{
            background: var(--brand-background);
            border-radius: var(--brand-border-radius);
            box-shadow: var(--brand-shadow);
            padding: 24px;
            border: 1px solid rgba(0,0,0,0.06);
            transition: all 0.3s ease;
        }}
        .brand-card:hover {{
            box-shadow: 0 8px 24px rgba(0,0,0,0.12);
            transform: translateY(-4px);
        }}
        
        .brand-card-primary {{
            background: var(--brand-primary);
            color: #FFFFFF;
            border-radius: var(--brand-border-radius);
            padding: 24px;
            box-shadow: var(--brand-shadow);
        }}
        .brand-card-primary a {{
            color: #FFFFFF;
            opacity: 0.9;
        }}
        .brand-card-primary a:hover {{
            opacity: 1;
        }}
        
        /* ========================================
           Headers & Footers
           ======================================== */
        
        .brand-header {{
            background: var(--brand-primary);
            color: #FFFFFF;
            padding: 16px 24px;
            border-radius: var(--brand-border-radius);
            box-shadow: var(--brand-shadow);
        }}
        .brand-header a {{
            color: #FFFFFF;
            text-decoration: none;
        }}
        
        .brand-footer {{
            background: var(--brand-secondary);
            color: #FFFFFF;
            padding: 16px 24px;
            border-radius: var(--brand-border-radius);
        }}
        .brand-footer a {{
            color: #FFFFFF;
            text-decoration: none;
        }}
        
        /* ========================================
           Badges
           ======================================== */
        
        .brand-badge {{
            background: var(--brand-accent);
            color: #FFFFFF;
            padding: 4px 12px;
            border-radius: 9999px;
            font-size: 12px;
            font-weight: 600;
            display: inline-block;
        }}
        
        .brand-badge-primary {{
            background: var(--brand-primary);
            color: #FFFFFF;
            padding: 4px 12px;
            border-radius: 9999px;
            font-size: 12px;
            font-weight: 600;
            display: inline-block;
        }}
        
        /* ========================================
           Forms
           ======================================== */
        
        .brand-input {{
            border: 2px solid var(--brand-primary);
            border-radius: var(--brand-border-radius);
            padding: 10px 16px;
            font-size: var(--brand-font-size);
            font-family: var(--brand-font);
            transition: all 0.3s ease;
            background: var(--brand-background);
            color: var(--brand-text);
            width: 100%;
            box-sizing: border-box;
        }}
        .brand-input:focus {{
            border-color: var(--brand-secondary);
            box-shadow: 0 0 0 4px rgba(124, 58, 237, 0.1);
            outline: none;
        }}
        .brand-input::placeholder {{
            color: #9CA3AF;
        }}
        
        .brand-select {{
            border: 2px solid var(--brand-primary);
            border-radius: var(--brand-border-radius);
            padding: 10px 16px;
            font-size: var(--brand-font-size);
            font-family: var(--brand-font);
            background: var(--brand-background);
            color: var(--brand-text);
            width: 100%;
        }}
        .brand-select:focus {{
            border-color: var(--brand-secondary);
            box-shadow: 0 0 0 4px rgba(124, 58, 237, 0.1);
            outline: none;
        }}
        
        .brand-label {{
            font-weight: 600;
            color: var(--brand-text);
            margin-bottom: 6px;
            display: block;
        }}
        
        /* ========================================
           Widget Specific
           ======================================== */
        
        .brand-widget {{
            border-radius: {branding.widget_border_radius};
            box-shadow: {branding.widget_shadow};
            background: {branding.background_color};
            border: 1px solid rgba(0,0,0,0.06);
            padding: 20px;
            font-family: var(--brand-font);
        }}
        
        .brand-widget-header {{
            background: {branding.widget_primary_color or branding.primary_color};
            color: #FFFFFF;
            padding: 16px 20px;
            border-radius: {branding.widget_border_radius} {branding.widget_border_radius} 0 0;
            margin: -20px -20px 16px -20px;
        }}
        
        .brand-widget-footer {{
            margin-top: 16px;
            padding-top: 12px;
            border-top: 1px solid rgba(0,0,0,0.06);
            font-size: 12px;
            color: #6B7280;
            text-align: center;
        }}
        
        /* ========================================
           Logo
           ======================================== */
        
        .brand-logo {{
            max-width: var(--brand-logo-width);
            max-height: var(--brand-logo-height);
            width: auto;
            height: auto;
        }}
        
        .brand-logo-container {{
            display: flex;
            align-items: center;
            gap: 12px;
        }}
        
        /* ========================================
           Responsive Utilities
           ======================================== */
        
        @media (max-width: 768px) {{
            .brand-header, .brand-footer {{
                padding: 12px 16px;
            }}
            .brand-card {{
                padding: 16px;
            }}
            .brand-btn-primary, .brand-btn-secondary, .brand-btn-outline {{
                padding: 8px 16px;
                font-size: 13px;
            }}
        }}
        """
        
        # Add dark mode CSS if enabled
        if branding.theme_type == "dark" or branding.dark_primary_color:
            css += f"""
            /* ========================================
               Dark Mode
               ======================================== */
            
            @media (prefers-color-scheme: dark) {{
                :root {{
                    --brand-primary: {branding.dark_primary_color or branding.primary_color};
                    --brand-secondary: {branding.dark_secondary_color or branding.secondary_color};
                    --brand-background: {branding.dark_background_color or '#111827'};
                    --brand-text: {branding.dark_text_color or '#F9FAFB'};
                }}
                
                .brand-card {{
                    background: #1F2937;
                    border-color: rgba(255,255,255,0.06);
                }}
                
                .brand-input {{
                    background: #1F2937;
                    color: #F9FAFB;
                    border-color: rgba(255,255,255,0.1);
                }}
                .brand-input:focus {{
                    border-color: var(--brand-primary);
                }}
            }}
            """
        
        # Add custom CSS if provided
        if branding.custom_css:
            css += f"""
            /* ========================================
               Custom CSS
               ======================================== */
            
            {branding.custom_css}
            """
        
        return css
    
    def generate_widget_css(self, branding: OrganizationBranding) -> str:
        """
        Generate CSS specifically for the embeddable widget.
        
        Args:
            branding: OrganizationBranding object
        
        Returns:
            CSS string for widget
        """
        primary = branding.widget_primary_color or branding.primary_color
        secondary = branding.widget_secondary_color or branding.secondary_color
        radius = branding.widget_border_radius
        shadow = branding.widget_shadow
        
        return f"""
        /* Widget CSS - Generated for {branding.brand_name or 'Organization'} */
        
        .widget-container {{
            font-family: '{branding.primary_font}', {branding.secondary_font}, system-ui, sans-serif;
            border-radius: {radius};
            box-shadow: {shadow};
            background: {branding.background_color};
            border: 1px solid rgba(0,0,0,0.08);
            padding: 20px;
            max-width: 100%;
            box-sizing: border-box;
        }}
        
        .widget-header {{
            background: {primary};
            color: #FFFFFF;
            padding: 16px 20px;
            border-radius: {radius} {radius} 0 0;
            margin: -20px -20px 16px -20px;
        }}
        
        .widget-title {{
            font-size: 20px;
            font-weight: 700;
            margin: 0;
        }}
        
        .widget-content {{
            padding: 4px 0;
        }}
        
        .widget-button {{
            background: {primary};
            color: #FFFFFF;
            border: none;
            padding: 10px 20px;
            border-radius: {radius};
            font-weight: 600;
            cursor: pointer;
            transition: all 0.2s ease;
            font-family: '{branding.primary_font}', system-ui, sans-serif;
        }}
        .widget-button:hover {{
            background: {secondary};
            transform: translateY(-1px);
        }}
        
        .widget-footer {{
            margin-top: 16px;
            padding-top: 12px;
            border-top: 1px solid rgba(0,0,0,0.06);
            font-size: 12px;
            color: #6B7280;
            text-align: center;
        }}
        
        .widget-powered {{
            font-size: 11px;
            color: #9CA3AF;
            text-align: center;
            margin-top: 8px;
        }}
        
        @media (max-width: 480px) {{
            .widget-container {{
                padding: 16px;
            }}
            .widget-header {{
                padding: 12px 16px;
                margin: -16px -16px 12px -16px;
            }}
            .widget-title {{
                font-size: 17px;
            }}
        }}
        """
    
    def generate_email_css(self, branding: OrganizationBranding) -> str:
        """
        Generate CSS for email templates.
        
        Args:
            branding: OrganizationBranding object
        
        Returns:
            CSS string for emails
        """
        header_color = branding.email_header_color or branding.primary_color
        
        return f"""
        /* Email CSS - Generated for {branding.brand_name or 'Organization'} */
        
        .email-container {{
            max-width: 600px;
            margin: 0 auto;
            font-family: '{branding.primary_font}', {branding.secondary_font}, system-ui, sans-serif;
            background: {branding.background_color};
            color: {branding.text_color};
        }}
        
        .email-header {{
            background: {header_color};
            color: #FFFFFF;
            padding: 24px 32px;
            border-radius: 8px 8px 0 0;
            text-align: center;
        }}
        
        .email-header h1 {{
            margin: 0;
            font-size: 24px;
        }}
        
        .email-body {{
            padding: 32px;
            background: #FFFFFF;
            border: 1px solid rgba(0,0,0,0.06);
            border-top: none;
            border-radius: 0 0 8px 8px;
        }}
        
        .email-footer {{
            text-align: center;
            padding: 16px;
            font-size: 12px;
            color: #6B7280;
            border-top: 1px solid rgba(0,0,0,0.06);
        }}
        """
    
    def validate_logo(self, file_data: bytes, filename: str) -> Tuple[bool, str]:
        """
        Validate logo file.
        
        Args:
            file_data: File data as bytes
            filename: Original filename
        
        Returns:
            Tuple of (is_valid, message)
        """
        # Check file size (max 5MB)
        if len(file_data) > 5 * 1024 * 1024:
            return False, "Logo file size exceeds 5MB limit"
        
        # Check file type
        ext = filename.split('.')[-1].lower()
        allowed_types = ['png', 'jpg', 'jpeg', 'svg', 'gif', 'webp']
        if ext not in allowed_types:
            return False, f"Unsupported file type: {ext}. Allowed: {', '.join(allowed_types)}"
        
        # Check dimensions for raster images
        if ext in ['png', 'jpg', 'jpeg', 'gif', 'webp']:
            try:
                from PIL import Image
                import io
                img = Image.open(io.BytesIO(file_data))
                width, height = img.size
                
                if width > 1200 or height > 600:
                    return False, f"Logo dimensions ({width}x{height}) exceed maximum (1200x600)"
                if width < 100 or height < 40:
                    return False, f"Logo dimensions ({width}x{height}) below minimum (100x40)"
                
                # Check aspect ratio
                ratio = width / height
                if ratio < 1.5 or ratio > 4.0:
                    return False, f"Logo aspect ratio ({ratio:.2f}) should be between 1.5 and 4.0"
                
            except ImportError:
                # PIL not available, skip dimension validation
                pass
            except Exception as e:
                pass
        
        return True, "Logo validated successfully"
    
    def generate_branding_preview(self, branding: OrganizationBranding) -> Dict[str, Any]:
        """
        Generate a preview of branding changes.
        
        Args:
            branding: OrganizationBranding object
        
        Returns:
            Preview data dictionary
        """
        css = self.generate_branding_css(branding)
        
        # Generate preview HTML
        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Branding Preview - {branding.brand_name or 'Brand'}</title>
            <style>
                /* Branding CSS */
                {css}
                
                /* Preview specific styles */
                body {{
                    margin: 0;
                    padding: 40px;
                    background: #F3F4F6;
                    font-family: var(--brand-font);
                }}
                .preview-container {{
                    max-width: 900px;
                    margin: 0 auto;
                }}
                .preview-section {{
                    margin-bottom: 30px;
                    padding: 20px;
                    background: var(--brand-background);
                    border-radius: var(--brand-border-radius);
                    box-shadow: var(--brand-shadow);
                }}
                .preview-section h2 {{
                    margin-top: 0;
                    color: var(--brand-text);
                    border-bottom: 2px solid var(--brand-primary);
                    padding-bottom: 8px;
                }}
                .preview-grid {{
                    display: grid;
                    grid-template-columns: 1fr 1fr;
                    gap: 16px;
                }}
                .preview-item {{
                    padding: 12px;
                    border: 1px solid rgba(0,0,0,0.06);
                    border-radius: var(--brand-border-radius);
                }}
                @media (max-width: 600px) {{
                    .preview-grid {{
                        grid-template-columns: 1fr;
                    }}
                }}
            </style>
        </head>
        <body>
            <div class="preview-container">
                <h1 style="color: var(--brand-primary); font-size: 32px; margin-bottom: 24px;">
                    🎨 Branding Preview
                </h1>
                
                <!-- Logo Section -->
                <div class="preview-section">
                    <h2>Logo</h2>
                    <div class="brand-logo-container">
                        <div style="padding:16px; border:1px dashed #D1D5DB; border-radius:8px; background:#F9FAFB;">
                            <span style="font-size:48px;">{branding.brand_name or '📝'}</span>
                            <div style="font-size:12px; color:#6B7280; margin-top:4px;">
                                {branding.logo_width}x{branding.logo_height}px
                            </div>
                        </div>
                    </div>
                </div>
                
                <!-- Colors Section -->
                <div class="preview-section">
                    <h2>Colors</h2>
                    <div class="preview-grid">
                        <div class="preview-item">
                            <div style="display:flex; align-items:center; gap:12px;">
                                <div style="width:40px; height:40px; border-radius:8px; background:{branding.primary_color}; border:1px solid #D1D5DB;"></div>
                                <div>
                                    <div style="font-weight:600;">Primary</div>
                                    <div style="font-size:12px; color:#6B7280;">{branding.primary_color}</div>
                                </div>
                            </div>
                        </div>
                        <div class="preview-item">
                            <div style="display:flex; align-items:center; gap:12px;">
                                <div style="width:40px; height:40px; border-radius:8px; background:{branding.secondary_color}; border:1px solid #D1D5DB;"></div>
                                <div>
                                    <div style="font-weight:600;">Secondary</div>
                                    <div style="font-size:12px; color:#6B7280;">{branding.secondary_color}</div>
                                </div>
                            </div>
                        </div>
                        <div class="preview-item">
                            <div style="display:flex; align-items:center; gap:12px;">
                                <div style="width:40px; height:40px; border-radius:8px; background:{branding.accent_color}; border:1px solid #D1D5DB;"></div>
                                <div>
                                    <div style="font-weight:600;">Accent</div>
                                    <div style="font-size:12px; color:#6B7280;">{branding.accent_color}</div>
                                </div>
                            </div>
                        </div>
                        <div class="preview-item">
                            <div style="display:flex; align-items:center; gap:12px;">
                                <div style="width:40px; height:40px; border-radius:8px; background:{branding.background_color}; border:1px solid #D1D5DB;"></div>
                                <div>
                                    <div style="font-weight:600;">Background</div>
                                    <div style="font-size:12px; color:#6B7280;">{branding.background_color}</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
                <!-- Buttons Section -->
                <div class="preview-section">
                    <h2>Buttons</h2>
                    <div style="display:flex; gap:12px; flex-wrap:wrap;">
                        <button class="brand-btn-primary">Primary Button</button>
                        <button class="brand-btn-secondary">Secondary Button</button>
                        <button class="brand-btn-outline">Outline Button</button>
                    </div>
                </div>
                
                <!-- Cards Section -->
                <div class="preview-section">
                    <h2>Cards</h2>
                    <div style="display:grid; grid-template-columns:1fr 1fr; gap:16px;">
                        <div class="brand-card">
                            <h3 style="color:var(--brand-primary);">Brand Card</h3>
                            <p style="color:var(--brand-text);">This is a card with your brand colors.</p>
                            <span class="brand-badge">Badge</span>
                        </div>
                        <div class="brand-card-primary">
                            <h3 style="color:#FFFFFF;">Primary Card</h3>
                            <p style="color:#FFFFFF; opacity:0.9;">This card uses your primary color.</p>
                            <span class="brand-badge" style="background:rgba(255,255,255,0.2);">Badge</span>
                        </div>
                    </div>
                </div>
                
                <!-- Typography Section -->
                <div class="preview-section">
                    <h2>Typography</h2>
                    <p><strong>Font:</strong> {branding.primary_font}</p>
                    <p><strong>Size:</strong> {branding.font_size}</p>
                    <p style="font-family:var(--brand-font);">
                        The quick brown fox jumps over the lazy dog.
                    </p>
                    <p style="font-family:var(--brand-font); font-weight:bold;">
                        Bold text example for headings.
                    </p>
                </div>
                
                <!-- Form Section -->
                <div class="preview-section">
                    <h2>Form Elements</h2>
                    <div style="display:grid; grid-template-columns:1fr 1fr; gap:16px;">
                        <div>
                            <label class="brand-label">Input Field</label>
                            <input type="text" class="brand-input" placeholder="Enter text here..." value="Sample text">
                        </div>
                        <div>
                            <label class="brand-label">Select Dropdown</label>
                            <select class="brand-select">
                                <option>Option 1</option>
                                <option>Option 2</option>
                                <option>Option 3</option>
                            </select>
                        </div>
                    </div>
                </div>
                
                <!-- Header/Footer Section -->
                <div class="preview-section">
                    <h2>Header & Footer</h2>
                    <div class="brand-header" style="margin-bottom:12px;">
                        Brand Header - {branding.brand_name or 'Organization'}
                    </div>
                    <div class="brand-footer">
                        Brand Footer - {branding.tagline or 'Tagline'}
                    </div>
                </div>
                
                <!-- Widget Section -->
                <div class="preview-section">
                    <h2>Widget Preview</h2>
                    <div class="brand-widget">
                        <div class="brand-widget-header">
                            <div class="widget-title">{branding.brand_name or 'Widget'}</div>
                        </div>
                        <div class="widget-content">
                            <p style="color:var(--brand-text);">This is how your branded widget will appear.</p>
                            <button class="widget-button">Widget Button</button>
                        </div>
                        <div class="widget-footer">
                            {branding.tagline or 'Powered by your brand'}
                        </div>
                        {"<div class='widget-powered'>Powered by Branding Service</div>" if not branding.hide_powered_by else ""}
                    </div>
                </div>
                
                <div style="text-align:center; padding:20px; color:#6B7280; font-size:12px;">
                    Preview generated at {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
                </div>
            </div>
        </body>
        </html>
        """
        
        return {
            'css': css,
            'html': html,
            'preview_url': f'/api/branding/{branding.organization_id}/css'
        }
    
    def get_cached_css(self, organization_id: str) -> Optional[str]:
        """Get cached CSS for organization."""
        return cache.get(f'{self.cache_prefix}css_{organization_id}')
    
    def cache_css(self, organization_id: str, css: str) -> None:
        """Cache CSS for organization."""
        cache.set(f'{self.cache_prefix}css_{organization_id}', css, 3600)  # 1 hour TTL
    
    def clear_css_cache(self, organization_id: str) -> None:
        """Clear cached CSS for organization."""
        cache.delete(f'{self.cache_prefix}css_{organization_id}')
    
    def generate_css_hash(self, branding: OrganizationBranding) -> str:
        """Generate a hash of the branding settings."""
        import json
        data = {
            'primary': branding.primary_color,
            'secondary': branding.secondary_color,
            'accent': branding.accent_color,
            'background': branding.background_color,
            'text': branding.text_color,
            'font': branding.primary_font,
            'theme': branding.theme_type
        }
        return hashlib.md5(json.dumps(data).encode()).hexdigest()[:8]